name: "Lint all YAML and workflow files in the repository"
on:
  pull_request:  # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Install yamllint
        run: pip install yamllint==1.38.0

      - name: Lint YAML files
        run: yamllint --no-warnings .

      - uses: reviewdog/action-actionlint@49cb3ce06e5d81452e14b38ad34e4b12a8acfe2b # v1.73.3

      # - name: Install gh-actionlint
      #   run: |
      #     gh extension install https://github.com/cschleiden/gh-actionlint
      #     gh actionlint -ignore '".+" line too long'
